ALTER DATABASE S9_Real SET EMERGENCY;

DBCC checkdb('S9_Real');

ALTER DATABASE S9_Real SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

DBCC CheckDB ('S9_Real', REPAIR_ALLOW_DATA_LOSS);

ALTER DATABASE S9_Real SET MULTI_USER;

ALTER DATABASE S9_Real SET online;